"""logs table

Revision ID: 7f21bd9700a9
Revises: 
Create Date: 2019-01-07 21:55:50.664255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f21bd9700a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logger', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('trace', sa.String(length=4096), nullable=True),
    sa.Column('msg', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_table')
    # ### end Alembic commands ###
